### ISSUE TITLE
non converta bene

### ISSUE THREAD

**Issue by Aniell4** [taralloxx/polliog-converter#1]
non ha workato.....

**Comment by taralloxx** [comment]
bro, non me ne frega un cazzo, per ulteriori info puoi contattarmi qui:

**Comment by Aniell4** [comment]
grazie 👍, ti contatterò qui

**Comment by taralloxx** [comment]
wow sei tu quello che si è lamentato del polliog converter

**Comment by Aniell4** [comment]
si sono io.... dimmi

**Comment by taralloxx** [comment]
vaffanculo

**Comment by Aniell4** [comment]
ma vaffanculo te, non worka nemmeno 🖕

**Comment by taralloxx** [comment]
bro, non me ne frega un cazzo, per ulteriori info puoi contattarmi qui: https://github.com/taralloxx/polliog-converter/issues/1

**Comment by Aniell4** [comment]
grazie 👍, ti contatterò qui: https://github.com/taralloxx/polliog-converter/issues/1#issue-1067605423

**Comment by Aniell4** [comment]
@polliog

**Comment by taralloxx** [comment]
@EatingSouls

**Comment by taralloxx** [comment]
mi scuso per il comportamento del mio collega poco professionale

**Comment by Aniell4** [comment]
mi scuso per il comportamento del mio collega poco professionale

**Comment by Aniell4** [comment]
![immagine](https://user-images.githubusercontent.com/43622438/144117278-9d4eb476-4f3d-4cdc-a837-7e83380949ae.png)

**Comment by taralloxx** [comment]
lol

**Comment by taralloxx** [comment]
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgimg.gateimg.com%2Fimage%2F1624359131881493888.png&f=1&nofb=1

**Comment by taralloxx** [comment]
[questa è un immagine](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgimg.gateimg.com%2Fimage%2F1624359131881493888.png&f=1&nofb=1)

**Comment by Aniell4** [comment]
[questa no](https://www.youtube.com/watch?v=EHBFKhLUVig)

**Comment by taralloxx** [comment]
cercasi ragazza che

**Comment by taralloxx** [comment]
[foto di ragazza che](https://youtu.be/529L8npycI8)

**Comment by Aniell4** [comment]
![immagine](https://user-images.githubusercontent.com/43622438/144118241-ad24d862-9ded-4bc3-a7ad-dd5ffb346450.png)

**Comment by taralloxx** [comment]
lol

**Comment by Aniell4** [comment]
lol

**Comment by Polliog** [comment]
ciao, sono stato menzionato riguardante il progetto?

**Comment by taralloxx** [comment]
no vaffanculo chi ti conosce

**Comment by Aniell4** [comment]
polliog converter

**Comment by EatingSouls** [comment]
CIao, un nuovo utente... penso potreste aggiungere una nuova funzione che fa automaticamente le telefonate a polliog e gli dice che è più basso della persona che sta usando il vostro sito.

**Comment by taralloxx** [comment]
https://youtu.be/D13Ob5Oq2ok

**Comment by Aniell4** [comment]
buona idea, io approverei 👍

**Comment by Polliog** [comment]
@EatingSouls la vostra affermazione nei confronti di polliog puo' essere reputata come bodyshaming la prego di astenersi da queste affermazioni nelle prossime Issues. Per altri problemi mi scriva qui: #1

**Comment by taralloxx** [comment]
cerco ragazza che

**Comment by Polliog** [comment]
Duplicate of #1

**Comment by Aniell4** [comment]
- [ ] aggiungere polliog

**Comment by Polliog** [comment]
![This is an image](https://raw.githubusercontent.com/Aniell4/Anime-Girls-Holding-Programming-Books/master/Javascript/Ninomae_Ina'nis_Holding_Eloquent_Javascript.jpg)

**Comment by taralloxx** [comment]
1. [``]([url]([url]([url](**`

@

- 

> _### `[url](url)`_

`**))))

**Comment by Aniell4** [comment]
1. 

- 

### ### 

> 

- **

1. 

- [ ]     

- [ ] ### ### [`_@###@_`](

- `[url]([url]([url]([url]([url]([url]([url]([url](url))))))))`

)

1.**

**Comment by Aniell4** [comment]
1. polliog è stato aggiunto correttamente

**Comment by taralloxx** [comment]
#
Duplicate of #

**Comment by EatingSouls** [comment]
> @EatingSouls la vostra affermazione nei confronti di polliog puo' essere reputata come bodyshaming la prego di astenersi da queste affermazioni nelle prossime Issues. Per altri problemi mi scriva qui: #1

Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.

**Comment by taralloxx** [comment]
Remember, contributions to this repository should follow our GitHub Community Guidelines.

**Comment by Aniell4** [comment]
**polliog ma bold**

**Comment by Aniell4** [comment]
@Polliog è stato rimosso

**Comment by Aniell4** [comment]
abbaimo fallito

**Comment by EatingSouls** [comment]
@Polliog è stato rimosso

**Comment by Polliog** [comment]
> > @EatingSouls la vostra affermazione nei confronti di polliog puo' essere reputata come bodyshaming la prego di astenersi da queste affermazioni nelle prossime Issues. Per altri problemi mi scriva qui: #1
> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.
> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.> 
> Hai ragione, mi scuso per cotale affermazione.... tuttavia però c'è da dire che il tuo essere bassi è un dato di fatto quindi non può essere considerato body shaming.
